
org: olofsson
app: react-app-herencia
name: react-starter
component: website

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist

package:
  exclude:
    - node_modules/**
    - venv/**
    - test/**
    - runs/**